/*
 * Generated by Cadeau Support.
 * * https://github.com/spldeolin/cadeau-support
 */
package com.swee.model.core.member.dao;

import org.apache.ibatis.annotations.Mapper;
import com.swee.model.core.api.CommonMapper;
import com.swee.model.core.member.model.RequestTrack;


/**
 * “请求轨迹”数据库映射
 *
 * @author Deolin 2018/8/30
 */
@Mapper
public interface RequestTrackMapper extends CommonMapper<RequestTrack> {

}