/*
 * Generated by Cadeau Support.
 *
 * https://github.com/spldeolin/cadeau-support
 */

package com.swee.model.core.member.service.impl;

import java.util.List;
import org.apache.commons.codec.digest.DigestUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import com.swee.model.core.api.CommonServiceImpl;
import com.swee.model.core.api.dto.Page;
import com.swee.model.core.api.dto.PageParam;
import com.swee.model.core.constant.CoupledConstant;
import com.swee.model.core.member.dao.UserMapper;
import com.swee.model.core.member.model.User;
import com.swee.model.core.member.service.UserService;
import com.swee.model.core.util.StringRandomUtils;
import lombok.extern.log4j.Log4j2;
import tk.mybatis.mapper.entity.Condition;

/**
 * “用户”业务实现
 *
 * @author Deolin 2018/5/28
 */
@Service
@Log4j2
public class UserServiceImpl extends CommonServiceImpl<User> implements UserService {

    @Autowired
    private UserMapper userMapper;

   // @Autowired
    //private PermissionService permissionService;

    @Autowired
    private RedisTemplate<String, Object> redisTemplate;

    @Override
    public Long createEX(User user) {
        // 盐、密码
        String salt = StringRandomUtils.generateVisibleAscii(32);
        user.setSalt(salt);
        String password = DigestUtils.sha512Hex(CoupledConstant.DEFAULT_PASSWORD_EX + salt);
        user.setPassword(password);

        // 能否登录
        user.setEnableSign(true);
        //userMapper.insertSelective(user);
        super.create(user);
        return user.getId();
    }

    @Override
    public User getEX(Long id) {
        return super.get(id).get();
    }


    @Override
    public void updateEX(User user) {
        Long id = user.getId();
    }

    @Override
    public void deleteEX(Long id) {

    }

    @Override
    public String deleteEX(List<Long> ids) {
        return null;
    }

    @Override
    public Page<User> page(PageParam pageParam) {
        return null;
    }

}