# 所有“占位符”属性均由profile指定
# core节点下属性映射到CoreProperties类

########################
##                    ##
##       Common       ##
##                    ##
########################

debug: 占位符

server:

  port: 占位符

spring:

  profiles.active: ${profile}

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: 占位符
      username: 占位符
      password: 占位符
      druid:
        initialSize: 2
        minIdle: 2
        maxActive: 30
        validationQuery: select 'x'
        test-on-borrow: true

  redis:
    host: 占位符
    port: 占位符
    password: 占位符
    timeout: 2000ms #2sec
    jedis:
     pool:
       max-active: 8
       max-wait: -1ms
       max-idle: 8
       min-idle: 0

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - com.swee.model.core.api.CommonMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:

  config: #未被覆盖时使用默认log4j2.yml

core:

  address: 占位符

  redis-namespace: sweeAuth

  time:
    default-date-pattern: yyyy-MM-dd
    default-time-pattern: HH:mm:ss
    default-datetime-pattern: yyyy-MM-dd HH:mm:ss
    serialize-java-util-date-to-timestamp: true

  file:
    mapping: 占位符
    location: 占位符

  email:
    server-host: smtp.163.com
    server-port: 25
    addresser-name: # TODO E-Mail
    addresser-email: # TODO E-Mail
    addresser-auth-code: # TODO E-Mail

---
########################
##                    ##
##     Devlopment     ##
##                    ##
########################

debug: true

server:
  port: 8081

spring:
  #active
  profiles: dev
  #nacos discovery
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8719
  application:
    name: swee-member

  #mysql 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/swee?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0


logging:

  config:

core:

  address: http://localhost:8091

  file:
    mapping: /static/
    location: C:/swee-auth-static/


